- hosts: test
  become: true
  tasks:
  - name: Install dependencies
    apt:
      pkg:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg 
      - lsb-release

  - name: get docker apt key
    ansible.builtin.apt_key:
      url:  https://download.docker.com/linux/ubuntu/gpg
      state: present 
  
  - name: add docker apt repo
    ansible.builtin.apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
      state: present
  
  - name: install docker
    apt:
      pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io

  - name: Add the user 
    ansible.builtin.user:
      name: pappy
      groups: docker
      append: yes